(schroot-mode-advised-make-process 'make-process :name "blipblorp" :command (list "xterm"))
(schroot-mode-advised-call-process 'call-process "xterm" nil nil nil)
(call-process (schroot-mode-pass-loc) nil nil nil "ubuntu" "xterm")
(schroot-mode-advised-start-process 'start-process "blipblorp" (get-buffer-create "*start-process*") "xterm" "--help")
(start-process "blipblorp" (get-buffer-create "*start-process*") "xterm" "screenfetch")
(apply 'start-process "blipblorp" (get-buffer-create "*start-process*") (schroot-mode-pass-loc) (append (list "ubuntu") nil (list "xterm") nil (list "--help")))
(apply 'start-proces)
(start-process "blipblorp" nil "/home/jacob/.emacs.d/schroot-mode/schroot_pass.sh" "ubuntu" "xterm")
(start-process "xterm" nil "/home/jacob/.emacs.d/schroot-mode/schroot_pass.sh" "ubuntu" "xterm" nil)
(apply 'start-process "blipblorp" nil (schroot-mode-pass-loc) "ubuntu" "xterm" nil)
(apply 'start-process "blipblorp" nil "/home/jacob/.emacs.d/schroot-mode/schroot_pass.sh" "ubuntu" "xterm" nil)
